package com.music.firebeats;

import com.google.common.collect.ImmutableMap;

/**
 * Provides access to the music tracks map see {@link #trackList} 
 */
public class MusicTracks
{
    /**
     * Map of all the tracks that are shared between osrs and rs3
     * {@link https://runescape.wiki/w/Music/track_list}
     */
	private static final ImmutableMap<String, String> trackList = new ImmutableMap
		.Builder<String, String>()
		.put("7th Realm", "https://runescape.wiki/index.php?title=File%3A7th_Realm.ogg")
		.put("Adventure", "")
		.put("Al Kharid", "")
		.put("All's Fairy in Love and War", "")
		.put("Alone", "")
		.put("Altar Ego", "")
		.put("Alternative Root", "")
		.put("Ambient Jungle", "")
		.put("Anywhere", "")
		.put("Arabian", "")
		.put("Arabian 2", "")
		.put("Arabian 3", "")
		.put("Arabique", "")
		.put("Arboretum", "")
		.put("Armadyl Alliance", "")
		.put("Armageddon", "")
		.put("Army of Darkness", "")
		.put("Arrival", "")
		.put("Artistry", "")
		.put("Assault and Battery", "")
		.put("Attack", "")
		.put("Attack 2", "")
		.put("Attack 3", "")
		.put("Attack 4", "")
		.put("Attack 5", "")
		.put("Attack 6", "")
		.put("Attention", "")
		.put("Autumn Voyage", "")
		.put("Aye Car Rum Ba", "")
		.put("Aztec", "")
		.put("Back to Life", "")
		.put("Background", "")
		.put("Ballad of Enchantment", "")
		.put("Ballad of the Basilisk", "")
		.put("Bandit Camp", "")
		.put("Bandos Battalion", "")
		.put("Barb Wire", "")
		.put("Barbarianism", "")
		.put("Barking Mad", "")
		.put("Baroque", "")
		.put("Beetle Juice", "")
		.put("Beyond", "")
		.put("Big Chords", "")
		.put("Blistering Barnacles", "")
		.put("Bloodbath", "")
		.put("Body Parts", "")
		.put("Bone Dance", "")
		.put("Bone Dry", "")
		.put("Book of Spells", "")
		.put("Borderland", "")
		.put("Breeze", "")
		.put("Brew Hoo Hoo", "")
		.put("Brimstail's Scales", "")
		.put("Bubble and Squeak", "")
		.put("Cabin Fever", "")
		.put("Camelot", "")
		.put("Castle Wars", "")
		.put("Catch Me If You Can", "")
		.put("Cave Background", "")
		.put("Cave of Beasts", "")
		.put("Cave of the Goblins", "")
		.put("Cavern", "")
		.put("Cellar Song", "")
		.put("Chain of Command", "")
		.put("Chamber", "")
		.put("Chickened Out", "")
		.put("Chompy Hunt", "")
		.put("City of the Dead", "")
		.put("Clan Wars", "")
		.put("Claustrophobia", "")
		.put("Close Quarters", "")
		.put("Competition", "")
		.put("Complication", "")
		.put("Contest", "")
		.put("Corporal Punishment", "")
		.put("Corridors of Power", "")
		.put("Courage", "")
		.put("Creature Cruelty", "")
		.put("Crystal Castle", "")
		.put("Crystal Cave", "")
		.put("Crystal Sword", "")
		.put("Cursed", "")
		.put("Dagannoth Dawn", "")
		.put("Dance of Death", "")
		.put("Dance of the Undead", "")
		.put("Dangerous", "")
		.put("Dangerous Road", "")
		.put("Dangerous Way", "")
		.put("Dark", "")
		.put("Darkmeyer", "")
		.put("Davy Jones's Locker", "")
		.put("Dead Can Dance", "")
		.put("Dead Quiet", "")
		.put("Deadlands", "")
		.put("Deep Down", "")
		.put("Deep Wildy", "")
		.put("Desert Heat", "")
		.put("Desert Voyage", "")
		.put("Diango's Little Helpers", "")
		.put("Dimension X", "")
		.put("Distant Land", "")
		.put("Distillery Hilarity", "")
		.put("Dogs of War", "")
		.put("Doorways", "")
		.put("Dorgeshuun City", "")
		.put("Dorgeshuun Deep", "")
		.put("Down and Out", "")
		.put("Down Below", "")
		.put("Down to Earth", "")
		.put("Dragontooth Island", "")
		.put("Dream", "")
		.put("Dreamstate", "")
		.put("Duel Arena", "")
		.put("Dunjun", "")
		.put("Dwarf Theme", "")
		.put("Dynasty", "")
		.put("Eagles' Peak", "")
		.put("Easter Jig", "")
		.put("Egypt", "")
		.put("Elven Mist", "")
		.put("Elven Seed", "")
		.put("Emotion", "")
		.put("Emperor", "")
		.put("Escape", "")
		.put("Espionage", "")
		.put("Everlasting", "")
		.put("Everlasting Fire", "")
		.put("Everywhere", "")
		.put("Evil Bob's Island", "")
		.put("Expanse", "")
		.put("Expecting", "")
		.put("Expedition", "")
		.put("Exposed", "")
		.put("Faerie", "")
		.put("Faithless", "")
		.put("Fanfare", "")
		.put("Fanfare 2", "")
		.put("Fanfare 3", "")
		.put("Fangs for the Memory", "")
		.put("Far Away", "")
		.put("Fe Fi Fo Fum", "")
		.put("Fear and Loathing", "")
		.put("Fenkenstrain's Refrain", "")
		.put("Fight or Flight", "")
		.put("Find My Way", "")
		.put("Fire and Brimstone", "")
		.put("Fishing", "")
		.put("Floating Free", "")
		.put("Flute Salad", "")
		.put("Food for Thought", "")
		.put("Forbidden", "")
		.put("Forest", "")
		.put("Forever", "")
		.put("Forgettable Melody", "")
		.put("Forgotten", "")
		.put("Frogland", "")
		.put("Frostbite", "")
		.put("Fruits de Mer", "")
		.put("Funny Bunnies", "")
		.put("Gaol", "")
		.put("Garden", "")
		.put("Garden of Autumn", "")
		.put("Garden of Spring", "")
		.put("Garden of Summer", "")
		.put("Garden of Winter", "")
		.put("Gnome King", "")
		.put("Gnome Village", "")
		.put("Gnome Village 2", "")
		.put("Gnomeball", "")
		.put("Goblin Game", "")
		.put("Goblin Village", "")
		.put("Golden Touch", "")
		.put("Greatness", "")
		.put("Grimly Fiendish", "")
		.put("Grip of the Talon", "")
		.put("Grotto", "")
		.put("Grumpy", "")
		.put("H.A.M. Fisted", "")
		.put("Harmony", "")
		.put("Harmony 2", "")
		.put("Haunted Mine", "")
		.put("Have a Blast", "")
		.put("Have an Ice Day", "")
		.put("Head to Head", "")
		.put("Heart and Mind", "")
		.put("Hell's Bells", "")
		.put("Hermit", "")
		.put("High Seas", "")
		.put("High Spirits", "")
		.put("Home Sweet Home", "")
		.put("Horizon", "")
		.put("Hypnotized", "")
		.put("Iban", "")
		.put("Ice Melody", "")
		.put("Illusive", "")
		.put("Impetuous", "")
		.put("In Between", "")
		.put("In the Brine", "")
		.put("In the Clink", "")
		.put("In the Manor", "")
		.put("In the Pits", "")
		.put("Inadequacy", "")
		.put("Incantation", "")
		.put("Insect Queen", "")
		.put("Inspiration", "")
		.put("Into the Abyss", "")
		.put("Intrepid", "")
		.put("Island Life", "")
		.put("Island of the Trolls", "")
		.put("Isle of Everywhere", "")
		.put("Jester Minute", "")
		.put("Jolly-R", "")
		.put("Joy of the Hunt", "")
		.put("Jungle Bells", "")
		.put("Jungle Hunt", "")
		.put("Jungle Island", "")
		.put("Jungle Island XMAS", "")
		.put("Jungle Troubles", "")
		.put("Jungly", "")
		.put("Jungly 2", "")
		.put("Jungly 3", "")
		.put("Karamja Jam", "")
		.put("Kingdom", "")
		.put("Knightly", "")
		.put("Knightmare", "")
		.put("La Mort", "")
		.put("Labyrinth", "")
		.put("Lair", "")
		.put("Lament", "")
		.put("Lament for the Hallowed", "")
		.put("Lament of Meiyerditch", "")
		.put("Land Down Under", "")
		.put("Land of Snow", "")
		.put("Land of the Dwarves", "")
		.put("Landlubber", "")
		.put("Last Stand", "")
		.put("Lasting", "")
		.put("Legend", "")
		.put("Legion", "")
		.put("Life's a Beach!", "")
		.put("Lighthouse", "")
		.put("Lightness", "")
		.put("Lightwalk", "")
		.put("Little Cave of Horrors", "")
		.put("Lonesome", "")
		.put("Long Ago", "")
		.put("Long Way Home", "")
		.put("Looking Back", "")
		.put("Lore and Order", "")
		.put("Lost Soul", "")
		.put("Lullaby", "")
		.put("Mad Eadgar", "")
		.put("Mage Arena", "")
		.put("Magic Dance", "")
		.put("Magic Magic Magic", "")
		.put("Magical Journey", "")
		.put("Major Miner", "")
		.put("Making Waves", "")
		.put("Malady", "")
		.put("March", "")
		.put("Marooned", "")
		.put("Marzipan", "")
		.put("Masquerade", "")
		.put("Mastermindless", "")
		.put("Mausoleum", "")
		.put("Meddling Kids", "")
		.put("Medieval", "")
		.put("Mellow", "")
		.put("Melodrama", "")
		.put("Meridian", "")
		.put("Method of Madness", "")
		.put("Miles Away", "")
		.put("Miracle Dance", "")
		.put("Mirage", "")
		.put("Miscellania", "")
		.put("Monarch Waltz", "")
		.put("Monkey Madness", "")
		.put("Monster Melee", "")
		.put("Moody", "")
		.put("Morytania", "")
		.put("Mouse Trap", "")
		.put("Mudskipper Melody", "")
		.put("Mutant Medley", "")
		.put("My Arm's Journey", "")
		.put("Narnode's Theme", "")
		.put("Natural", "")
		.put("Neverland", "")
		.put("Newbie Melody", "")
		.put("Night of the Vampyre", "")
		.put("Nightfall", "")
		.put("No Way Out", "")
		.put("Nomad", "")
		.put("Norse Code", "")
		.put("Null and Void", "")
		.put("Ogre the Top", "")
		.put("On the Up", "")
		.put("On the Wing", "")
		.put("Oriental", "")
		.put("Out of the Deep", "")
		.put("Overpass", "")
		.put("Overture", "")
		.put("Parade", "")
		.put("Path of Peril", "")
		.put("Pathways", "")
		.put("Pest Control", "")
		.put("Pharaoh's Tomb", "")
		.put("Phasmatys", "")
		.put("Pheasant Peasant", "")
		.put("Pinball Wizard", "")
		.put("Pirates of Penance", "")
		.put("Pirates of Peril", "")
		.put("Poles Apart", "")
		.put("Prime Time", "")
		.put("Principality", "")
		.put("Quest", "")
		.put("Rat a Tat Tat", "")
		.put("Rat Hunt", "")
		.put("Ready for Battle", "")
		.put("Regal", "")
		.put("Reggae", "")
		.put("Reggae 2", "")
		.put("Rellekka", "")
		.put("Right on Track", "")
		.put("Righteousness", "")
		.put("Rising Damp", "")
		.put("Riverside", "")
		.put("Roc and Roll", "")
		.put("Roll the Bones", "")
		.put("Romancing the Crone", "")
		.put("Romper Chomper", "")
		.put("Roots and Flutes", "")
		.put("Royale", "")
		.put("Rune Essence", "")
		.put("Sad Meadow", "")
		.put("Safety in Numbers", "")
		.put("Saga", "")
		.put("Sarcophagus", "")
		.put("Sarim's Vermin", "")
		.put("Scape Cave", "")
		.put("Scape Hunter", "")
		.put("Scape Main", "")
		.put("Scape Original", "")
		.put("Scape Sad", "")
		.put("Scape Santa", "")
		.put("Scape Scared", "")
		.put("Scape Soft", "")
		.put("Scape Wild", "")
		.put("Scarab", "")
		.put("School's Out", "")
		.put("Sea Shanty", "")
		.put("Sea Shanty 2", "")
		.put("Sea Shanty XMAS", "")
		.put("Serenade", "")
		.put("Serene", "")
		.put("Settlement", "")
		.put("Shadowland", "")
		.put("Shine", "")
		.put("Shining", "")
		.put("Shining Spirit", "")
		.put("Shipwrecked", "")
		.put("Showdown", "")
		.put("Sigmund's Showdown", "")
		.put("Slice of Silent Movie", "")
		.put("Slice of Station", "")
		.put("Slither and Thither", "")
		.put("Slug a Bug Ball", "")
		.put("Sojourn", "")
		.put("Soundscape", "")
		.put("Sphinx", "")
		.put("Spirit", "")
		.put("Spirits of Elid", "")
		.put("Splendour", "")
		.put("Spooky", "")
		.put("Spooky 2", "")
		.put("Spooky Jungle", "")
		.put("Stagnant", "")
		.put("Starlight", "")
		.put("Start", "")
		.put("Stillness", "")
		.put("Storm Brew", "")
		.put("Stranded", "")
		.put("Strange Place", "")
		.put("Stratosphere", "")
		.put("Strength of Saradomin", "")
		.put("Subterranea", "")
		.put("Sunburn", "")
		.put("Superstition", "")
		.put("Suspicious", "")
		.put("Tale of Keldagrim", "")
		.put("Talking Forest", "")
		.put("Tears of Guthix", "")
		.put("Technology", "")
		.put("Temple", "")
		.put("Temple of Light", "")
		.put("The Cellar Dwellers", "")
		.put("The Chosen", "")
		.put("The Depths", "")
		.put("The Desert", "")
		.put("The Desolate Isle", "")
		.put("The Enchanter", "")
		.put("The Far Side", "")
		.put("The Galleon", "")
		.put("The Genie", "")
		.put("The Golem", "")
		.put("The Last Shanty", "")
		.put("The Lost Melody", "")
		.put("The Lost Tribe", "")
		.put("The Lunar Isle", "")
		.put("The Mad Mole", "")
		.put("The Mollusc Menace", "")
		.put("The Monsters Below", "")
		.put("The Navigator", "")
		.put("The Nightmare Continues", "")
		.put("The Noble Rodent", "")
		.put("The Other Side", "")
		.put("The Power of Tears", "")
		.put("The Rogues' Den", "")
		.put("The Shadow", "")
		.put("The Slayer", "")
		.put("The Terrible Caverns", "")
		.put("The Terrible Tower", "")
		.put("The Terrible Tunnels", "")
		.put("The Tower", "")
		.put("The Trade Parade", "")
		.put("Theme", "")
		.put("Throne of the Demon", "")
		.put("Time Out", "")
		.put("Time to Mine", "")
		.put("Tiptoe", "")
		.put("Title Fight", "")
		.put("Tomb Raider", "")
		.put("Tomorrow", "")
		.put("Too Many Cooks...", "")
		.put("Trawler", "")
		.put("Trawler Minor", "")
		.put("Tree Spirits", "")
		.put("Tremble", "")
		.put("Tribal", "")
		.put("Tribal 2", "")
		.put("Tribal Background", "")
		.put("Trinity", "")
		.put("Trouble Brewing", "")
		.put("Troubled", "")
		.put("Twilight", "")
		.put("TzHaar!", "")
		.put("Undead Dungeon", "")
		.put("Undercurrent", "")
		.put("Underground", "")
		.put("Underground Pass", "")
		.put("Understanding", "")
		.put("Unknown Land", "")
		.put("Untouchable", "")
		.put("Upcoming", "")
		.put("Upir Likhyi", "")
		.put("Venture", "")
		.put("Venture 2", "")
		.put("Victory is Mine", "")
		.put("Village", "")
		.put("Vision", "")
		.put("Volcanic Vikings", "")
		.put("Voodoo Cult", "")
		.put("Voyage", "")
		.put("Waking Dream", "")
		.put("Wander", "")
		.put("Warrior", "")
		.put("Warriors' Guild", "")
		.put("Waterfall", "")
		.put("Waterlogged", "")
		.put("Way of the Enchanter", "")
		.put("Wayward", "")
		.put("Well of Voyage", "")
		.put("Where Eagles Lair", "")
		.put("Wild Side", "")
		.put("Wilderness", "")
		.put("Wilderness 2", "")
		.put("Wilderness 3", "")
		.put("Wildwood", "")
		.put("Winter Funfair", "")
		.put("Witching", "")
		.put("Woe of the Wyvern", "")
		.put("Wolf Mountain", "")
		.put("Wonder", "")
		.put("Wonderous", "")
		.put("Woodland", "")
		.put("Work Work Work", "")
		.put("Workshop", "")
		.put("Wrath and Ruin", "")
		.put("Xenophobe", "")
		.put("Yesteryear", "")
		.put("Zamorak Zoo", "")
		.put("Zealot", "")
		.put("Zogre Dance", "")
		.put("Zombiism", "")
		.build();

    /**
     * Checks {@link #trackList} for the specified track.
     * @param name the name of the track to lookup
     * @return true if the track exists, false otherwise
     */
	public static Boolean ContainsTrack(String name)
	{
		return trackList.containsKey(name);
	}

    /**
     * Gets the {@code link} for the specified track.
     * <p>
     * Note: the link is not a direct download of the track.
     * it is only a link to the file page containing the download
     * @param name the track name used to get the link from {@link #trackList}
     * @return the string of the tracks link, otherwise null if the track does not exist in {@link #trackList}
     */
	public static String GetTrackLink(String name)
	{
		return trackList.get(name);
	}

}



